version: '3'
services:
  ### Nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: ${NGINX_DOCKERFILE}
    ports:
    - "${NGINX_PORT}:80"
    links:
      - client
      - server

  ### Server
  server:
    build:
      context: ./server
      dockerfile: ${SERVER_DOCKERFILE}
    volumes:
    - ./server:/usr/src/app
    ports:
    - "${SERVER_PORT}:4000"
    links:
    - postgres
    depends_on:
    - postgres
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      DEBUG: ${SERVER_DEBUG}
      DEV: ${DEV}

  ## Client
  client:
    build:
      context: ./client
      dockerfile: ${CLIENT_DOCKERFILE}
    volumes:
    - ./client:/usr/src/app
    ports:
    - "${CLIENT_PORT}:3000"
    depends_on:
    - server
    environment:
      REACT_APP_GRAPHQL: ${REACT_APP_GRAPHQL}
      DEBUG: ${CLIENT_DEBUG}
      DEV: ${DEV}

  ## Postgres
  postgres:
    build: db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  ## PGAdmin
  pgadmin:
    image: dpage/pgadmin4
    ports:
    - "${PGADMIN_PORT}:80"
    depends_on:
    - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}